# Generated by Django 6.0 on 2026-01-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_permission_role_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
